export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAILURE = "CREATE_CLIENT_FAILURE";
export const GET_ALL_CLIENT_REQUEST = "GET_ALL_CLIENT_REQUEST";
export const GET_ALL_CLIENT_SUCCESS = "GET_ALL_CLIENT_SUCCESS";
export const GET_ALL_CLIENT_FAIL = "GET_ALL_CLIENT_FAIL";

export const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAILURE = "GET_CLIENT_FAILURE";
export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAILURE = "UPDATE_CLIENT_FAILURE";
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILURE = "DELETE_CLIENT_FAILURE";
export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAILURE = "CREATE_PROPERTY_FAILURE";
export const RESET_CREATE_PROPERTY_STATE = "RESET_CREATE_PROPERTY_STATE";

export const ADD_PROPERTY_TO_CLIENT_REQUEST = "ADD_PROPERTY_TO_CLIENT_REQUEST";
export const ADD_PROPERTY_TO_CLIENT_SUCCESS = "ADD_PROPERTY_TO_CLIENT_SUCCESS";
export const ADD_PROPERTY_TO_CLIENT_FAILURE = "ADD_PROPERTY_TO_CLIENT_FAILURE";

export const GET_PROPERTIES_BY_CLIENT_REQUEST =
  "GET_PROPERTIES_BY_CLIENT_REQUEST";
export const GET_PROPERTIES_BY_CLIENT_SUCCESS =
  "GET_PROPERTIES_BY_CLIENT_SUCCESS";
export const GET_PROPERTIES_BY_CLIENT_FAILURE =
  "GET_PROPERTIES_BY_CLIENT_FAILURE";

export const GET_PROPERTIES_BY_TYPE_REQUEST = "GET_PROPERTIES_BY_TYPE_REQUEST";
export const GET_PROPERTIES_BY_TYPE_SUCCESS = "GET_PROPERTIES_BY_TYPE_SUCCESS";
export const GET_PROPERTIES_BY_TYPE_FAILURE = "GET_PROPERTIES_BY_TYPE_FAILURE";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAILURE = "UPDATE_PROPERTY_FAILURE";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";

export const GET_FILTERED_PROPERTIES_REQUEST =
  "GET_FILTERED_PROPERTIES_REQUEST";
export const GET_FILTERED_PROPERTIES_SUCCESS =
  "GET_FILTERED_PROPERTIES_SUCCESS";
export const GET_FILTERED_PROPERTIES_FAILURE =
  "GET_FILTERED_PROPERTIES_FAILURE";

export const CREATE_LEASE_REQUEST = "CREATE_LEASE_REQUEST";
export const CREATE_LEASE_SUCCESS = "CREATE_LEASE_SUCCESS";
export const CREATE_LEASE_FAILURE = "CREATE_LEASE_FAILURE";

export const GET_PROPERTIES_BY_ID_REQUEST = "GET_PROPERTIES_BY_ID_REQUEST";
export const GET_PROPERTIES_BY_ID_SUCCESS = "GET_PROPERTIES_BY_ID_SUCCESS";
export const GET_PROPERTIES_BY_ID_FAILURE = "GET_PROPERTIES_BY_ID_FAILURE";

export const SET_PROPERTIES = "SET_PROPERTIES";
export const SET_FILTERS = "SET_FILTERS";
export const RESET_PROPERTIES = "RESET_PROPERTIES";

export const GET_ALL_PROPERTIES_REQUEST = "GET_ALL_PROPERTIES_REQUEST";
export const GET_ALL_PROPERTIES_SUCCESS = "GET_ALL_PROPERTIES_SUCCESS";
export const GET_ALL_PROPERTIES_FAILURE = "GET_ALL_PROPERTIES_FAILURE";

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";

export const GET_PAYMENTS_BY_LEASE_REQUEST = "GET_PAYMENTS_BY_LEASE_REQUEST";
export const GET_PAYMENTS_BY_LEASE_SUCCESS = "GET_PAYMENTS_BY_LEASE_SUCCESS";
export const GET_PAYMENTS_BY_LEASE_FAILURE = "GET_PAYMENTS_BY_LEASE_FAILURE";

export const GET_PAYMENTS_BY_CLIENT_REQUEST = "GET_PAYMENTS_BY_CLIENT_REQUEST";
export const GET_PAYMENTS_BY_CLIENT_SUCCESS = "GET_PAYMENTS_BY_CLIENT_SUCCESS";
export const GET_PAYMENTS_BY_CLIENT_FAILURE = "GET_PAYMENTS_BY_CLIENT_FAILURE";

export const GET_ALL_LEASES_REQUEST = "GET_ALL_LEASES_REQUEST";
export const GET_ALL_LEASES_SUCCESS = "GET_ALL_LEASES_SUCCESS";
export const GET_ALL_LEASES_FAILURE = "GET_ALL_LEASES_FAILURE";

export const GET_LEASES_BY_CLIENT_REQUEST = "GET_LEASES_BY_CLIENT_REQUEST";
export const GET_LEASES_BY_CLIENT_SUCCESS = "GET_LEASES_BY_CLIENT_SUCCESS";
export const GET_LEASES_BY_CLIENT_FAILURE = "GET_LEASES_BY_CLIENT_FAILURE";

export const GET_ALL_PAYMENTS_REQUEST = "GET_ALL_PAYMENTS_REQUEST";
export const GET_ALL_PAYMENTS_SUCCESS = "GET_ALL_PAYMENTS_SUCCESS";
export const GET_ALL_PAYMENTS_FAILURE = "GET_ALL_PAYMENTS_FAILURE";

export const CREATE_GUARANTORS_REQUEST = "CREATE_GUARANTORS_REQUEST";
export const CREATE_GUARANTORS_SUCCESS = "CREATE_GUARANTORS_SUCCESS";
export const CREATE_GUARANTORS_FAIL = "CREATE_GUARANTORS_FAIL";
export const GET_GUARANTORS_REQUEST = "GET_GUARANTORS_BY_LEASE_REQUEST";
export const GET_GUARANTORS_SUCCESS = "GET_GUARANTORS_BY_LEASE_SUCCESS";
export const GET_GUARANTORS_FAIL = "GET_GUARANTORS_BY_LEASE_FAILURE";

