export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_CLIENT_REQUEST =  "CREATE_CLIENT_REQUEST"
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS"
export const CREATE_CLIENT_FAILURE=  "CREATE_CLIENT_FAILURE"
export const GET_ALL_CLIENT_REQUEST = "GET_ALL_CLIENT_REQUEST"
export const GET_ALL_CLIENT_SUCCESS = "GET_ALL_CLIENT_SUCCESS"
export const GET_ALL_CLIENT_FAIL = "GET_ALL_CLIENT_FAIL"

export const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST"
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS"
export const GET_CLIENT_FAILURE= "GET_CLIENT_FAILURE"
export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST"
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS"
export const UPDATE_CLIENT_FAILURE = "UPDATE_CLIENT_FAILURE"
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST"
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS"
export const DELETE_CLIENT_FAILURE = "DELETE_CLIENT_FAILURE"
export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAILURE = "CREATE_PROPERTY_FAILURE";
export const RESET_CREATE_PROPERTY_STATE = "RESET_CREATE_PROPERTY_STATE";

export const ADD_PROPERTY_TO_CLIENT_REQUEST = 'ADD_PROPERTY_TO_CLIENT_REQUEST';
export const ADD_PROPERTY_TO_CLIENT_SUCCESS = 'ADD_PROPERTY_TO_CLIENT_SUCCESS';
export const ADD_PROPERTY_TO_CLIENT_FAILURE = 'ADD_PROPERTY_TO_CLIENT_FAILURE';